<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report_type }} Report — {{ $branch->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; margin: 30px; }
        .header { text-align: center; border-bottom: 2px solid #4F46E5; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { color: #4F46E5; margin: 0 0 4px; font-size: 18px; }
        .header h2 { margin: 0; font-size: 14px; color: #555; }
        .header p { margin: 4px 0 0; color: #888; font-size: 10px; }
        .section { margin-bottom: 20px; }
        .section h3 { background: #F3F4F6; padding: 6px 10px; margin: 0 0 8px; font-size: 11px; text-transform: uppercase; color: #555; border-left: 3px solid #4F46E5; }
        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 16px; }
        .stat-box { border: 1px solid #E5E7EB; border-radius: 6px; padding: 10px; text-align: center; }
        .stat-box .num { font-size: 22px; font-weight: bold; color: #4F46E5; }
        .stat-box .lbl { font-size: 9px; color: #888; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; font-size: 10px; }
        th { background: #F9FAFB; border: 1px solid #E5E7EB; padding: 5px 8px; text-align: left; }
        td { border: 1px solid #E5E7EB; padding: 5px 8px; }
        tr:nth-child(even) td { background: #FAFAFA; }
        .footer { margin-top: 30px; border-top: 1px solid #E5E7EB; padding-top: 10px; font-size: 9px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sacca Aviation Training Institute</h1>
        <h2>{{ $report_type }} Report — {{ $branch->name }}</h2>
        <p>Period: {{ $from->format('d M Y') }} to {{ $to->format('d M Y') }} &bull; Generated: {{ $generated_at->format('d M Y h:i A') }}</p>
    </div>

    <div class="section">
        <h3>Summary Statistics</h3>
        <div class="stats-grid">
            <div class="stat-box"><div class="num">{{ $data['total_students'] }}</div><div class="lbl">Total Students</div></div>
            <div class="stat-box"><div class="num">{{ $data['total_staff'] }}</div><div class="lbl">Total Staff</div></div>
            <div class="stat-box"><div class="num">{{ $data['active_enrollments'] }}</div><div class="lbl">Active Enrollments</div></div>
            <div class="stat-box"><div class="num">{{ $data['students_placed'] }}</div><div class="lbl">Students Placed</div></div>
            <div class="stat-box"><div class="num">{{ $data['average_attendance_pct'] }}%</div><div class="lbl">Avg. Attendance</div></div>
        </div>
    </div>

    <div class="section">
        <h3>Student Register</h3>
        <table>
            <thead><tr><th>#</th><th>Name</th><th>Email</th><th>ID</th></tr></thead>
            <tbody>
                @foreach($data['students_list'] as $i => $student)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $student['name'] }}</td>
                    <td>{{ $student['email'] }}</td>
                    <td>{{ $student['employee_id'] ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>Staff Register</h3>
        <table>
            <thead><tr><th>#</th><th>Name</th><th>Role</th><th>Employee ID</th></tr></thead>
            <tbody>
                @foreach($data['staff_list'] as $i => $staff)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $staff['name'] }}</td>
                    <td>{{ $staff['role'] }}</td>
                    <td>{{ $staff['employee_id'] ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        This report is generated by Sacca Institute Management System. Report Type: {{ $report_type }}. Branch Code: {{ $branch->code }}.
    </div>
</body>
</html>
