<div>
    @if(session('success'))
        <div class="mb-4 bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg text-sm">{{ session('success') }}</div>
    @endif

    <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
        <h3 class="font-semibold text-gray-800 mb-4">Generate Compliance Report</h3>
        <form wire:submit="generate" class="grid grid-cols-2 gap-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Report Type *</label>
                <select wire:model="report_type" class="w-full px-4 py-2 border border-gray-300 rounded-lg text-sm">
                    <option value="TAHDCO">TAHDCO Report</option>
                    <option value="SCDD">SCDD Report</option>
                    <option value="monthly_summary">Monthly Summary</option>
                    <option value="annual">Annual Report</option>
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Branch *</label>
                <select wire:model="branch_id" class="w-full px-4 py-2 border border-gray-300 rounded-lg text-sm">
                    <option value="">Select branch…</option>
                    @foreach($branches as $branch)
                        <option value="{{ $branch->id }}">{{ $branch->name }}</option>
                    @endforeach
                </select>
                @error('branch_id') <p class="mt-1 text-xs text-red-500">{{ $message }}</p> @enderror
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">From Date *</label>
                <input wire:model="period_from" type="date" class="w-full px-4 py-2 border border-gray-300 rounded-lg text-sm">
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">To Date *</label>
                <input wire:model="period_to" type="date" class="w-full px-4 py-2 border border-gray-300 rounded-lg text-sm">
            </div>
            <div class="col-span-2">
                <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg text-sm font-medium">
                    <span wire:loading.remove>Generate PDF Report</span>
                    <span wire:loading>Generating…</span>
                </button>
            </div>
        </form>
    </div>

    <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-200">
                <tr>
                    <th class="px-6 py-3 text-left font-semibold text-gray-600">Type</th>
                    <th class="px-6 py-3 text-left font-semibold text-gray-600">Branch</th>
                    <th class="px-6 py-3 text-left font-semibold text-gray-600">Period</th>
                    <th class="px-6 py-3 text-left font-semibold text-gray-600">Generated By</th>
                    <th class="px-6 py-3 text-left font-semibold text-gray-600">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse($reports as $report)
                <tr class="hover:bg-gray-50">
                    <td class="px-6 py-3"><span class="bg-indigo-50 text-indigo-700 text-xs px-2 py-1 rounded-full font-medium">{{ $report->report_type }}</span></td>
                    <td class="px-6 py-3 text-gray-600">{{ $report->branch->name }}</td>
                    <td class="px-6 py-3 text-gray-500 text-xs">{{ $report->period_from->format('d M Y') }} – {{ $report->period_to->format('d M Y') }}</td>
                    <td class="px-6 py-3 text-gray-500 text-xs">{{ $report->generatedBy->name }}</td>
                    <td class="px-6 py-3">
                        @if($report->file_path)
                            <a href="{{ Storage::url($report->file_path) }}" target="_blank" class="text-indigo-600 hover:underline text-xs font-medium">Download PDF</a>
                        @endif
                    </td>
                </tr>
                @empty
                <tr><td colspan="5" class="px-6 py-10 text-center text-gray-400">No reports generated yet.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
